spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
jwt:
  secret: ${JWT_SECRET_KEY}
  expirationTimeMillis: ${JWT_EXPIRATION_TIME_MILLIS}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
logging:
  level:
    root: INFO