spring:
  application:
    name: gallery
  profiles:
    active: dev
server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
      base-path: /actuator # default aslında bu, yine de yaz.
  endpoint:
    health:
      show-details: always